# [Info]
# 左上角标题
site_name: CosHub
site_url: https://Elliottt001.github.io
site_author: 张瑞喆
site_description: Zhang rz的个人网站

# 禁用目录 URL 以修复图片路径问题（可选）
# use_directory_urls: false

# [Navigtion]
nav:
  - 主页: 
    - 封面: index.md
    - 🕑更新记录: changelog.md
    - 🕑倒计时: 
      - ✍高考倒计时: countdown/gee/gee.html
      - 🎂生日倒计时: countdown/birthday/birthday.html

  - 个人:
    - ME/index.md
    - 思考: 
      - 大学教育与人生发展: ME/THOUGHT/colledge-education-and-my-future.md
    - SDFZ:
      - 永远的391: ME/SDFZ/391forever.md
      - 附中回忆录: ME/SDFZ/sdfz_memorior.md
    - ZJU:
      - 面试经历: 
        - 学生会: ME/ZJU/interview/interview for SU.md
        - 专业确认: ME/ZJU/interview/interview for major.md
        - 启真问学: ME/ZJU/interview/interview-for-qzwx.md
        - X-lab问卷: ME/ZJU/interview/x-lab-application.md
      - 计划:
        - 24寒假: ME/ZJU/plan/plan-for-24winter-holiday.md
      - 学习:
        - 资源: ME/ZJU/learn/resoure.md
    - 随笔:
      - 2024-11: ME/ESSAY/2024-11.md
      - 2024-12: ME/ESSAY/2024-12.md
      - 2025-01: ME/ESSAY/2025-01.md

  - 数理:
    - KNOWLEDGE/index.md
    - 微积分:
      - 知识体系: KNOWLEDGE/calculus/knowledge-frame-of-calculus.md
      - 方法总结: KNOWLEDGE/calculus/summary-of-calculus.md
      - 思想方法: KNOWLEDGE/calculus/thought-for-calculus.md
      - 级数: KNOWLEDGE/calculus/series-sdk.md
      - 矢量代数与空间解析几何: KNOWLEDGE/calculus/vector-algebra.md
      - 多元函数微分学: KNOWLEDGE/calculus/differential-calculus-of-multivariate-function.md
    - 线性代数:
      - 知识体系: KNOWLEDGE/linear-algebra/knowledge-frame-of-LA.md
      - 方法总结: KNOWLEDGE/linear-algebra/summary-of-LA.md 
    - 离散数学:
      - Chap1 逻辑和证明: KNOWLEDGE/discrete/chap-1.md
    - 大学物理:
      - 大雾下课程信息: KNOWLEDGE/physics/index.md
      - 考试复习笔记: KNOWLEDGE/physics/exam-review.md
      - 动力学: KNOWLEDGE/physics/dynamics-motion.md
      - 电磁学: KNOWLEDGE/physics/electricity.md
      - 电磁学公式物理量总结: KNOWLEDGE/physics/electricity-summary.md
    - 概率论与数理统计:
      - 课程信息: KNOWLEDGE/probability/index.md
      
  - 开发:
    - CS/index.md
    - 实战开发: 
      - 项目组织: CS/develop/project.md
      - Git规范: CS/develop/git.md
      - 编程风格: CS/develop/programming.md
    - 前端开发:
      - 学习笔记:
        - 内容速查: CS/front-end/note/index.md
        - web技术基础: CS/front-end/note/web/build.md
        - HTML: CS/front-end/note/html/tag.md
        - CSS: CS/front-end/note/css/css-note.md
      - 环境配置及知识:
        - JavaScript: CS/front-end/note/js.md
    - 后端开发:
      - 学习笔记:
        - 数据库: CS/back-end/note/db/db.md
        - Golang: none.md
        - Java: CS/back-end/note/java/methods.md
    - 编程语言:
      - C/C++:
        - C语言: 
          - 学习笔记: CS/pl/C_Cpp/C/c-note.md
          - 错题整理: CS/pl/C_Cpp/C/c-errors-and-tips.md
          - 链表: CS/pl/C_Cpp/C/linkedList.md
        - C++:
          - 课程信息: CS/pl/C_Cpp/cpp/index.md
          - Lecture 0:Introduction: CS/pl/C_Cpp/cpp/intro.md
          - Lecture 1&2:Streams: CS/pl/C_Cpp/cpp/streams.md
          - Lecture 3:Standard Template Library: CS/pl/C_Cpp/cpp/stl.md
          - Lecture 4:Modern C++ Types: CS/pl/C_Cpp/cpp/type.md
          - Guest Lecture:Template metaprogramming: CS/pl/C_Cpp/cpp/tmp.md
          - Varibles & Synatax: CS/pl/C_Cpp/cpp/basic.md
          - Keywords: CS/pl/C_Cpp/cpp/keyword.md
      - Python:
        - python主页: CS/pl/Python/index.md
        - 基础语法: CS/pl/Python/py-basic-grammar.md
        - 数据容器: CS/pl/Python/py-sequence.md
        - 面向对象: CS/pl/Python/py-oop.md
        - 文件基础: CS/pl/Python/file-basic.md
        - 文件进阶: CS/pl/Python/file-advance.md
        - 标准库积累: CS/pl/Python/modules.md
        - 项目开发: CS/pl/Python/development-in-py.md
        - 百日打卡: CS/pl/Python/clock-in.md
        - 伊力笔记: CS/pl/Python/python-note.md
      - Go:
        - GORM: CS/pl/go/db.md
    - 计算机系统:
      - 数字逻辑设计: 
        - Chapter 1 数字系统与信息: CS/system/digital-design/chap1.md
        - Chapter 2 组合逻辑电路: CS/system/digital-design/chap2.md
        - Chapter 3 组合逻辑电路的设计: CS/system/digital-design/chap3.md
      - 计算机组成原理:
        - 课程信息: CS/system/priciples/index.md
        - Chapter 1 计算机系统概述: CS/system/priciples/chap1.md
        - 汇编语言指令概述: CS/system/priciples/instructions.md
        - 数的表示: CS/system/priciples/number_representation.md
        
    - 算法相关: 
      - 数据结构基础:
        - 课程信息: CS/algorithm/fds/index.md
        - 算法分析: CS/algorithm/fds/chap2.md
        - Chapter 3 ADT & Stack & Queue: CS/algorithm/fds/chap3.md
        - Chapter 4 Tree: CS/algorithm/fds/chap4.md
        - Chapter 5 Graph: CS/algorithm/fds/graph.md
        - Chapter 6 Hash Table: CS/algorithm/fds/hashing.md
        - Chapter 7 Sorting: CS/algorithm/fds/sorting.md

      - 高级数据结构与算法分析:
        - 课程信息: CS/algorithm/ads/index.md
        - 考试复习笔记: CS/algorithm/ads/exam-review.md
        - AVL树和Splay树: CS/algorithm/ads/avl-tree_splay-tree.md
        - 红黑树: CS/algorithm/ads/redblack_tree.md
        - B+树: CS/algorithm/ads/bplus_tree.md
        - 倒排表: CS/algorithm/ads/inverted_file_index.md
        - 左偏树和斜堆: CS/algorithm/ads/leftist_heap.md
        - 二项队列: CS/algorithm/ads/binomial_queue.md
        - 回溯法: CS/algorithm/ads/backtracking.md
        - 分治合并法: CS/algorithm/ads/divide_conquer.md
        - 动态规划: CS/algorithm/ads/dynamic_programming.md
      - Misc: CS/algorithm/misc.md
      - Sort: CS/algorithm/sort.md
    - 数据科学:
      - 大数据挖掘:
        - 课程信息: CS/data/mining-massive-data/index.md
        - Map Reduce and Spark: CS/data/mining-massive-data/mapreduce-and-spark.md
        - Frequent Itemsets Mining: CS/data/mining-massive-data/frequent-itemsets-mining.md
        - LSH(Locality Sensitive Hashing): CS/data/mining-massive-data/lsh.md

    - 操作系统:
      - Linux:
        - WSL备忘录: CS/OS/linux/wsl-record.md
        - 虚拟机备忘录: CS/OS/linux/vm-record.md
        - WSL操作指南: CS/OS/linux/wsl-note.md
        - GitHub Copilot: CS/OS/linux/github-copilot.md
        - Clash Verge Rev 安装/配环境指南: CS/OS/linux/clash-verge-rev.md
      - Windows物理机一: CS/OS/windows/win-note.md
      - Windows物理机二: CS/OS/windows/win1.md
    - 网络安全:
      - 首页: CS/CTF/index.md
      - 基础: CS/CTF/basic.md
      - CTF&AAA简介: CS/CTF/ctf-and-aaa.md
      - 实验报告:
        - lab0: CS/CTF/lab0.md
    - 区块链:
      - 基础引入: CS/blockchain/background.md
      - 技术原理: CS/blockchain/theory.md
      - 实际应用: CS/blockchain/usage.md
      - 比特币: CS/blockchain/bitcoin.md
      - 数字货币: CS/blockchain/digital-currency.md
      - 以太坊: CS/blockchain/ethereum.md
    - 人工智能:
      - 机器学习:
        - RUC讲稿: CS/AI/ML/机器学习讲稿.ipynb
      - AI: CS/AI/AI.md
      - ANN: CS/AI/ANN.md
      - DL: CS/AI/DL.md
      - ML: CS/AI/ML.md
      - Turing: CS/AI/Turing.md
    - X-lab 相关:
      - 创始人王振阳分享 - X-lab简介: LAB/x-lab.md
      - 张博学长分享 - 思维高度与前沿创新: LAB/zhangbo.md
      - 任炜烨学长 - 企业级开发经验分享: LAB/rwy.md
      - 江林益学长分享 - 科研深造之路: LAB/01.md
      - 转正大会: LAB/转正大会.md
    - 实用工具:
      - shell: 
        - 笔记一: CS/Tools/shell.md
        - 笔记二: CS/Tools/shell-new.md
      - CSS: CS/Tools/CSS.md
      - HTML: CS/Tools/HTML.md
      - Git&GitHub: CS/Tools/Git & GitHub.md
      - Docker: CS/Tools/docker.md
      - Markdown: CS/Tools/Markdown(obsidian).md
      - LaTeX: CS/Tools/LaTeX.md
      - Linux: CS/Tools/Linux.md
      - vim: CS/Tools/vim.md
      - GDB: CS/Tools/GDB.md
      - Obsidian: CS/Tools/Obsidian.md
      - Mkdocs: 
        - MkDocs: CS/Tools/mkdocs.md
        - MkDocs图像: CS/Tools/mkdocs-images-copy.md
      - Makefile: CS/Tools/makefile.md
      - Anaconda: CS/Tools/anaconda.md
      - VMware: CS/Tools/vmware-linux.md
    - 杂七杂八:
      - 想了解的东西: CS/Misc/things-i-wanna-know.md
      - 正则表达式: CS/Misc/regex.md
      - 网络相关: CS/Misc/network.md
      - 一些快捷键: CS/Misc/shortcuts.md
      - 硬件by AI: CS/Misc/hardware.md

  - 机器人:
    - ROBOTICS/index.md
    - FTC教程:
      - 主页: ROBOTICS/FTCTutorial/index.md
      - 1.Java基础:
        - 1.1程序入门: ROBOTICS/FTCTutorial/1.1程序入门.md
        - 1.2.变量、常量与数据类型: ROBOTICS/FTCTutorial/1.2.变量、常量与数据类型.md
        - 1.3.程序控制结构: ROBOTICS/FTCTutorial/1.3.程序控制结构.md
        - 1.4.面向对象编程基础: ROBOTICS/FTCTutorial/1.4.面向对象编程基础.md
      - 2.FTC基础:
        - 2.1FTC游戏手柄使用指南: ROBOTICS/FTCTutorial/2.1FTC游戏手柄使用指南.md
        - 2.2FTC遥测系统使用指南: ROBOTICS/FTCTutorial/2.2FTC遥测系统使用指南.md
      - 3.操作模式:
        - 3.1操作模式概念解析: ROBOTICS/FTCTutorial/3.1操作模式概念解析.md
        - 3.2操作模式注解: ROBOTICS/FTCTutorial/3.2操作模式注解.md
        - 3.3线性操作模式基础: ROBOTICS/FTCTutorial/3.3线性操作模式基础.md
        - 3.4常见的驱动控制模式: ROBOTICS/FTCTutorial/3.4常见的驱动控制模式.md
      - 4.硬件基础:
        - 4.1伺服电机使用指南: ROBOTICS/FTCTutorial/4.1伺服电机使用指南.md
        - 4.2机器人硬件组织: ROBOTICS/FTCTutorial/4.2机器人硬件组织.md
      - 5.传感器:
        - 5.1陀螺仪使用指南: ROBOTICS/FTCTutorial/5.1陀螺仪使用指南.md
      - 进阶:
        - PID: ROBOTICS/FTCTutorial/PID.md
        - PedroPathing: ROBOTICS/FTCTutorial/PedroPathing.md
        - FileSystem: ROBOTICS/FTCTutorial/FileSystem.md
        - OpmodesFiles: ROBOTICS/FTCTutorial/OpmodesFiles.md
        - BLUE_Far_12ball: ROBOTICS/FTCTutorial/BLUE_Far_12ball.md
      
  - 金融:
    - FINANCE/index.md
    - 微观经济学:
      - 课程信息: FINANCE/micro/index.md
      - 绪论: FINANCE/micro/start.md
      - 价格理论: FINANCE/micro/price-theory.md
      - 弹性理论: FINANCE/micro/theory-of-elasticity.md
      - 消费者行为理论: FINANCE/micro/consumer-behavior-theory.md

    - 宏观经济学:
      - 课程信息: FINANCE/macro/index.md
      - 宏观经济的基本指标及其衡量:
        - 国内生产总值: FINANCE/macro/gdp.md
        - 消费、储蓄、投资、政府购买、净出口: FINANCE/macro/other-variables.md
        - 货币需求和货币供给: FINANCE/macro/currency.md

    - 零碎自学:
      - 金本位: FINANCE/DIY/gold-standard.md
  - 阅读:
    - BOOK/index.md
    - 文学名著:
      - 山茶文具店: BOOK/fictions/山茶文具店.md
      - 暮光之城: BOOK/fictions/twilight.md
    - 专业书籍:
      - 1.md
  - 公众:
    - PUBLIC/index.md
    - 秀米: PUBLIC/xiumi.md
    - 哪吒: PUBLIC/nezha.md
    - 工作汇报: PUBLIC/work-report.md
    - 报销工作注意事项: PUBLIC/reimbursement.md
    - ZJU-vlog: PUBLIC/zju-vlog.md

# [UI]
# [top]
theme:
  name: material

  favicon: images/favicon_circle.png
  custom_dir: overrides # 用来搞评论的，参考 https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  font: False


  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 右侧目录随页面滑动
    - toc.follow 
    # # 打开 Tab 时左侧目录全部展开
    # # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    # - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
    # 将公告标记为已读
    - announce.dismiss
  icon:
    logo: material/library-outline
    # [添加 GitHub 仓库]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    # 块: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition-icons-octicons
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      # note: fontawesome/solid/note-sticky
      # abstract: fontawesome/solid/book
      # info: fontawesome/solid/circle-info
      # tip: fontawesome/solid/bullhorn
      # success: fontawesome/solid/check
      # question: fontawesome/solid/circle-question
      # warning: fontawesome/solid/triangle-exclamation
      # failure: fontawesome/solid/bomb
      # danger: fontawesome/solid/skull
      # bug: fontawesome/solid/robot
      # example: fontawesome/solid/flask
      # quote: fontawesome/solid/quote-left
    # 注释: https://squidfunk.github.io/mkdocs-material/reference/annotations/#in-content-tabs-tab-2
    annotation: material/checkbox-marked-circle-auto-outline
  
# [点击按钮跳转至 GitHub 修改 Markdown 源文件]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/
# [top-right corner]
# [添加 GitHub 仓库]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/Elliottt001/Elliottt001.github.io
repo_name: CosHub
# [bottom-left corner]
# [版权说明]
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#copyright-notice
copyright: >
  Copyright © 2024 张瑞喆 All rights reserved.
  
  <a href="#__consent">Change cookie settings</a>
# [bottom-right corner]
extra:
  # [添加社交网络图标和链接]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  # 搜索图标：https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  # name 会在鼠标悬浮时提示
  social: # icons
    - name: GitHub | Elliottt001
      icon: fontawesome/brands/github
      link: https://github.com/Elliottt001
  generator: false

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
    actions:
      - accept
      - manage  
  
# [Extensions]
plugins:
  # [搜索功能]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # 之前中文搜索是 Insider 的功能（https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/），现在好像已经是默认功能了，
  - search:
      lang:
        - zh
        - en
        - es
  # [给单篇文章添加标签]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/#meta.tags
  - tags
  - glightbox #图片放大
  - statistics #统计页面字数、代码行数、阅读时间
    #https://github.com/TonyCrane/mkdocs-statistics-plugin  
  - git-revision-date-localized:
        type: datetime
        timezone: Asia/Shanghai
        locale: zh
        enable_creation_date: true
        exclude:
            - index.md
            - writeups/AAA.md
  - rss
  - changelog
  - minify:
      minify_html: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 5
  - admonition #应用admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite #添加了对内联代码块的语法突出显示的支持
  - pymdownx.snippets #使用简单语法将任意文件的内容嵌入到文档
  - pymdownx.superfences: #允许代码和内容块任意嵌套，包括警告、选项卡、列表和所有其他元素
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details #admonition可以折叠

  - attr_list #允许使用特殊语法将 HTML 属性和 CSS 类添加到几乎每个Markdown 内联和块级元素。
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.keys #添加了一个简单的语法来允许呈现键盘按键和组合 

  # Caret 、 Mark和Tilde扩展添加了使用简单语法突出显示文本并定义下标和上标的功能。
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.critic #允许使用Critic 标记来突出显示文档中添加、删除或更新的部分，即跟踪 Markdown 语法的更改。

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  # 相关内容或者代码块可以分组展示
  - pymdownx.tabbed:
      alternate_style: true
  
  # 允许使用任务清单即- []      
  - pymdownx.tasklist:
      custom_checkbox: true
  
  # 允许渲染公式，还需要添加mathjax配置和JavaScript      
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#arithmatex
  - pymdownx.arithmatex:
      generic: true

  - def_list #使用各类表格
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  - sane_lists
  - pymdownx.magiclink


extra_css:
  - mkdocs/css/card.css
  - mkdocs/css/flink.css
  - mkdocs/css/custom.css
  - mkdocs/css/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css

extra_javascript:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
